import javax.swing.JOptionPane;

public class HoroScope {
public static void main(String[] args) {
String question = JOptionPane.showInputDialog(null, "What is your Zodiac Sign?");

if (question.equalsIgnoreCase("scorpio")) {
	JOptionPane.showMessageDialog(null, "Upside: Scorpio exhibit\n extreme self-control in many areas,\n and as a result expect that of those around them.\n They are disciplined, protective and are very interested in others.\n They give of themselves but do expect the same in return.\n Scorpio males and females both need to be the leaders, \nand excel at problem solving \nand troubleshooting projects and situations.\r\n" + 
			"\r\n" + 
			"Downside: Scorpio invented the term ‘vendetta’.\n Once a Scorpio is crossed, they don’t forget it. \nFemale Scorpio are worse about this than they \nothers, often going decades without making\n amends with friends and family. Scorpio also \ntend to be pessimistic, often seeing threats where \nthere aren’t any, which can make them suspicious\n, stubborn and paranoid without cause.");
}	else if (question.equalsIgnoreCase("cancer")) {
	JOptionPane.showMessageDialog(null, "Upside: Cancer have an offbeat sense of humor\n, often finding something humorous that others don’t.\n They are extremely good listeners and have a heart for the problems of others.\n In fact, many gravitate toward this sign because they intuitively know that a Cancer will understand.\n When a Cancer becomes your friend you can be sure that they are truly your friend and will not consider using someone to their own benefit.\n Cancer tend to be dependable and reliable.\n They will tell you anything you want to know about them without blinking an eye as they are drawn to honesty in others as well as themselves.\n\r\n" + 
				"\r\n" + 
				"Downside: This sign can be moody, clingy, and often become incredibly insecure if they feel that they are about to lose the friendship or love of someone close to them.\n If the situation calls for it, they will lie, but often this dishonesty stems\n from a deep insecurity about being alone.");
}	else if (question.equalsIgnoreCase("aries")) {
	JOptionPane.showMessageDialog(null, "Upside: Highly energetic, and has no problem working\n long hours on a single project. Often take the initiative experiencing\n new breakthroughs and discoveries. Aries are thorough, painstaking, and have\n a knack for precise records and clarity. They live hard, love hard, and play hard.\r\n" + 
			"\r\n" + 
			"Downside: Aries have tunnel vision when working on\n a project which can make them seem selfish. They\n can become impatient with those who are not similar to themselves temperamentally\n and intellectually. The dedication to a project can become stubbornness, possessiveness,\n and can lead to a withdrawn and sullen attitude. Many Aries who do not feel\n acknowledged for their accomplishments become sarcastic and rude.");
}	else if (question.equalsIgnoreCase("leo")) {
JOptionPane.showMessageDialog(null, "Upside: Leo tend to be honest and decent people, opting to do the\n right thing regardless of the situation. They love organization so that they\n can find their ‘things’. Leos love material goods and luxury and want those that\n they love to experience this wealth as well. Leo are generally\n accepting of everyone initially and make decent, lasting relationships.\r\n" + 
		"\r\n" + 
		"Downside: Leo have a great sense of\n self-worth which can cross the line into arrogance.\n Leo can tend toward extravagance if they are not satisfied with what they\n have. Because they like to be in charge, they can\n often become smothering to their mates and friends,\n which may leave them alone (which Leo hates). Divorce and loss\n are devastating to this sign as they are all about the community and family.");
}	else if (question.equalsIgnoreCase("Virgo")) {
	JOptionPane.showMessageDialog(null, "Upside: Virgo have a heart for their fellow man. They are kind,\n patient and love to laugh. They are not loud ‘look at me’ signs, but rather prefer\n to be the strong, silent type. They are creative thinkers and true family oriented people.\n Male Virgo, once they are committed to relationship never walk away\n (unless there is a betrayal, and even then it isn’t written in stone). Female\n Virgo are dedicated parents, often parenting other children in the neighborhood.\r\n" + 
			"\r\n" + 
			"Downside: Virgo are particularly attentive to health; theirs,\n yours, everyone’s, which can often lead to obsessive behaviors toward health\n (hypochondria). They can also be judgmental and critical of those that\n they feel are not living up to their potential, or are going about a\n project in an inefficient way. Virgo are opinionated\n and have no problem sharing their opinions, even when they should not");
}	else if (question.equalsIgnoreCase("capricorn")) {
	JOptionPane.showMessageDialog(null, "Upside: Capricorns are the superheroes when It\n comes to making realistic, logical decisions. Their ability to cut through the red\n tape and see the bottom line is what makes them a real asset to any relationship or occupation\n where teamwork is valued. Capricorn are family oriented, but will keep their\n distance if the family is perceived to be violent, harmful, or unfulfilling. Capricorn have a dry sense of humor and\n their sarcastic wit is only appreciated by those who find humor everywhere. Highly\n intellectual, good with numbers and analysis, this sign is not often loud, \nbut they are most definitely the muscle and the power behind the very successful machine.\r\n" + 
			"\r\n" + 
			"Downside: Because they are so dedicated to the big picture and the minute details, \nthey can seem dull to others, who don’t understand the active internal nature of the Capricorn.\n While seeming almost emotionless on the surface, the Capricorn’s mind is always \nrunning on overdrive. They can often seem selfish and stingy, keeping information to themselves, or \nstrategically withholding information for their own gain. Often they can be the less imaginative\n of the signs and refuse to face the facts about a situation because it\n would signal that they were wrong about something (which they hate).");
}	else if (question.equalsIgnoreCase("Aquarius")) {
	JOptionPane.showMessageDialog(null, "Upside: Aquarians are among the friendliest of the signs, making\n friends everywhere. They are often chosen among co-workers\n and family for special awards and honors because of their ability to\n network. Highly intelligent they are energetic and talented, often using their\n abilities to help others. Despite their extensive people skills, they often\n crave alone time to reflect and think about things. Meditation is\n recommended for this sign as it helps to maintain that sense of alone time, while \nat the same time a feeling of connectedness with something greater than themselves.\r\n" + 
			"\r\n" + 
			"Downside: If this sign does not have alone time and time to do\n much desired reflection, they become dour, emotionless, and even are prone to\n depressive interludes. They can become highly resentful if they believe that their voice is\n not being truly heard or valued. Because they do self-reflect, this sign can become\n quite eccentric in some of the hobbies that they pursue, or activities they enjoy.");
}	else if (question.equalsIgnoreCase("Sagittarius")) {
	JOptionPane.showMessageDialog(null, "Upside: Sagittarians are highly intelligent and love to be around\n intelligent people. They enjoy learning new things, traveling\n to new places, and experiencing unique adventures. Creativity is\n at the core of who they are and Sagittarians are often creating and\n recreating their living situations, work situations, and human relationships. Sagittarians are\n spiritually inclined and are among the types that would travel\n to the Himalayas to commune with the monks, or take the book, Eat, Pray,\n Love and go to each spot mentioned in its pages to seek their own enlightenment.\r\n" + 
			"\r\n" + 
			"Downside: Confining a Sagittarian and not allowing\n for ample space to roam will make this sign rude, and uncooperative.\n Sagittarians often come up with unrealistic, big plans, but lack the\n ability to follow through with them. This isn’t because they aren’t capable,\n but rather they can become sidetracked chasing another avenue of adventure or\n thought. Sagittarians are about the bigger picture and details often bog them down and bore them.");
}	else if (question.equalsIgnoreCase("Gemini")) {
	JOptionPane.showMessageDialog(null, "Upside: Gemini are great conversationalists, and are charming people. Interesting to speak with, Gemini know a\n little bit about a lot of things. They have a great sense of humor \nand are generally optimistic people. Gemini often make their own fun, despising boredom.\r\n" + 
			"\r\n" + 
			"Downside: Gemini like to be the center of attention; always. When \nthey perceive the situation to not be in their favor, they leave it. This can \ninclude relationships, careers, and friendships. Because of this need to\n be seen as important, Gemini will sometimes stretch the truth. When \nthey are focused only on themselves they can be largely unsympathetic and rude. Male Gemini \ntend to change jobs often, and female Gemini change partners often due to boredom.");
}	else if (question.equalsIgnoreCase("Taurus")) {
	JOptionPane.showMessageDialog(null, "Upside: Taurus people almost \nalways finish what they start. They are deliberate thinkers and when making decisions usually \nmake the right one. Taurus are generally adaptable, adjusting easily to \nnew circumstances especially if there is the reward of luxury, comfort, \nor sensual reward. This sign loves to laugh and spend time with family.\r\n" + 
			"\r\n" + 
			"Downside: Taurus can be stubborn and ‘bullish’ about ideas that they’ve adopted, which can also make them difficult \nto get along with when attempting to \ncooperate on a shared project. Taurus needs to be the leader and to be held in high esteem. \nIf they are not, they refuse to work, often finding small ways to \nsabotage projects, relationships, or undermine authority that they deem unworthy of leadership.");
}	else if (question.equalsIgnoreCase("pisces")) {
	JOptionPane.showMessageDialog(null, "Upside: Pisces are empathetic people, often feeling badly for \nsomeone whose life is not going well. They feel the need to reach out to those who \nare less fortunate and will often find themselves involved in drama that \nthey hadn’t intended. They are kind, caring individuals who feel everything \ndeeply, even though you would not know it on the surface. They can be creative\n and imaginative when they believe that they have support to make those leaps.\r\n" + 
			"\r\n" + 
			"Downside: Because they feel everything so intensely, this sign can often become a \nclinical worrier. They will worry that they are not worrying. This tendency \nto worry also leads to indecision on their part, fearing that if they make\n a decision that others disagree with that they will have upset someone. Pisces \ndon’t like to hurt people’s feelings and as such become conflicted when they \nhave to make decisions. They do not do well as leaders, but are impressive \nsupport personnel. Sometimes the have a lack of follow through due to this\n indecisiveness and require a gentle nudge from other signs to complete tasks on time.");
}	else if (question.equalsIgnoreCase("Libra")) {
	JOptionPane.showMessageDialog(null, "Upside: Libra all have a sense of fair play about them and become completely upset if they \nperceive that something is unfair or unjust. They are prone\n to talking for long periods of time about their favorite subjects. Generally the \ndecisions that a Libra makes are the ones that will benefit the most people. \nLibra are often self-sacrificing for the good of the team or the family.\r\n" + 
			"\r\n" + 
			"Downside: Because Libra take so long \nto make decisions it can be perceived as laziness, or \nabsent- mindedness. Libra, because of their sense of justice and fair \nplay, will often become argumentative to the exclusion of decorum or \nappropriateness. Libra don’t like to be in charge, but they like to have a say and to be heard.");
}	else {
	JOptionPane.showMessageDialog(null,"That not a Zodiac Sign, silly you!");
}
}
}